version: "2.0"

networks:
  socks5_net:

services:
  socks5-service:
    image: xukeawsl/socks5-server:latest
    container_name: socks5-server
    ports:
      - 1080:1080
    volumes:
      - /var/log/socks5:/root/socks5-service/build/logs
    networks:
      - socks5_net
    environment:
      - TZ=Asia/Shanghai
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    privileged: true