name: Release Socks Server (Multi-Platform)

on:
  push:
    tags:
      - 'v*' # 匹配以 'v' 开头的标签，例如 v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }} # 使用矩阵策略
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-18.04, windows-latest] # 支持的平台
        include:
          - os: ubuntu-20.04
            release_name: ubuntu-20.04
            artifact_name: socks-server-ubuntu-20.04.tar.gz
            binary_name: socks_server
            package_command: tar -czvf socks-server-ubuntu-20.04.tar.gz -C release .
          - os: ubuntu-22.04
            release_name: ubuntu-22.04
            artifact_name: socks-server-ubuntu-22.04.tar.gz
            binary_name: socks_server
            package_command: tar -czvf socks-server-ubuntu-22.04.tar.gz -C release .
          - os: ubuntu-18.04
            release_name: ubuntu-18.04
            artifact_name: socks-server-ubuntu-18.04.tar.gz
            binary_name: socks_server
            package_command: tar -czvf socks-server-ubuntu-18.04.tar.gz -C release .
          - os: windows-latest
            release_name: windows-latest
            artifact_name: socks-server-windows-x64.zip
            binary_name: socks_server.exe
            package_command: 7z a socks-server-windows-x64.zip .\release\*

    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 安装构建工具
    - name: Install dependencies
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install 7zip
        else
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
        fi

    # 3. 构建项目
    - name: Build
      shell: bash
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .

    # 4. 调试：打印 bin 目录中的文件列表
    - name: Debug - Print bin directory
      shell: bash
      run: |
        echo "Files in bin directory:"
        ls -R

    # 5. 检查发布是否存在
    - name: Check if release exists
      id: check_release
      uses: actions/github-script@v6
      with:
        script: |
          const { data: releases } = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const releaseExists = releases.some(release => release.tag_name === process.env.GITHUB_REF_NAME);
          core.setOutput('exists', releaseExists);

    # 6. 创建发布（如果不存在）
    - name: Create Release
      if: steps.check_release.outputs.exists == 'false'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }} (${{ matrix.release_name }})
        draft: false
        prerelease: false

    # 7. 打包 /bin/socks-server 和 config.json
    - name: Package Binary and Config
      run: |
        mkdir -p release/bin
        cp ./bin/${{ matrix.binary_name }} release/bin/${{ matrix.binary_name }}
        cp ./config.json release/
        echo "Files in release directory:"
        ls -R release
        ${{ matrix.package_command }}

    # 8. 上传打包文件到 GitHub Releases
    - name: Upload Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.check_release.outputs.upload_url || steps.create_release.outputs.upload_url }}
        asset_path: ./${{ matrix.artifact_name }}
        asset_name: ${{ matrix.artifact_name }}
        asset_content_type: application/octet-stream